name: deploy-node

on:
  workflow_call:
    inputs:
      build_folder:
        description: "Build output folder"
        required: false
        default: "build"
        type: string
      env_property:
        description: "Environment property"
        required: false
        default: "VITE_APP_VERSION"
        type: string
      version_type:
        description: "major | minor | patch | none"
        required: false
        type: string
      package_manager:
        description: "npm | yarn | bun | pnpm"
        required: false
        default: "npm"
        type: string
      add_branch_name:
        required: false
        type: boolean
        default: true
      add_build_number:
        required: false
        type: boolean
        default: true
    secrets:
      ACCESS_GITHUB_TOKEN:
        required: true

jobs:
  setup-version:
    uses: jenesei-software/.github/.github/workflows/setup-version.yml@main
    with:
      version_type: ${{ inputs.version_type }}
      branch_name: ${{ github.ref_name }}
      add_branch_name: ${{ inputs.add_branch_name }}
      add_build_number: ${{ inputs.add_build_number }}
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

  setup-build:
    needs: [setup-version]
    uses: jenesei-software/.github/.github/workflows/setup-build.yml@main
    with:
      full_version: ${{ needs.setup-version.outputs.full_version }}
      package_manager: ${{ inputs.package_manager }}
      env_property: ${{ inputs.env_property }}
      build_folder: ${{ inputs.build_folder }}
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

  deploy:
    needs: [setup-build, setup-version]
    runs-on: ubuntu-latest
    env:
      FULL_VERSION: ${{ needs.setup-version.outputs.full_version }}
      BRANCH_NAME: ${{ github.ref_name }}
      ENV_PROPERTY: ${{ inputs.env_property }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-build
          path: build

      - name: Write version to package.json and .env
        run: |
          node -e "let p=require('./package.json'); p.version='${{ env.FULL_VERSION }}'; require('fs').writeFileSync('./package.json', JSON.stringify(p, null, 2));"

          touch .env
          if grep -q '^${{ env.ENV_PROPERTY }}=' .env; then
            sed -i "s/^${{ env.ENV_PROPERTY }}=.*/${{ env.ENV_PROPERTY }}=${{ env.FULL_VERSION }}/" .env
          else
            echo "${{ env.ENV_PROPERTY }}=${{ env.FULL_VERSION }}" >> .env
          fi

      - name: Git Commit & Push Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -u
          if ! git diff --cached --quiet; then
            git commit -m "version: ${{ env.FULL_VERSION }}"
          fi
          git tag -a "v${{ env.FULL_VERSION }}" -m "version: ${{ env.FULL_VERSION }}"
          git push origin HEAD:${{ env.BRANCH_NAME }}
          git push origin "v${{ env.FULL_VERSION }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          publish_branch: build_${{ env.BRANCH_NAME }}
          publish_dir: build
          force_orphan: true
