name: Frontend Build

on:
  workflow_call:
    inputs:
      version_type:
        description: "major | minor | patch | none"
        required: false
        type: string
      package_manager:
        description: "npm | yarn | bun"
        required: false
        default: "npm"
        type: string
    secrets:
      ACCESS_GITHUB_TOKEN:
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

  setup:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Bun
        if: inputs.package_manager == 'bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

  setup-git:
    uses: jenesei-software/.github/.github/workflows/setup-git.yml@main
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

  setup-npmrc:
    uses: jenesei-software/.github/.github/workflows/setup-npmrc.yml@main
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

  version:
    needs: checkout
    uses: jenesei-software/.github/.github/workflows/setup-version.yml@main
    with:
      version_type: ${{ inputs.version_type }}
      branch_name: ${{ needs.checkout.outputs.branch_name }}
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

  dependencies:
    needs: [setup-git, version, setup-npmrc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/yarn
            ~/.bun/install/cache
          key: |
            r1/${{ runner.os }}/${{ inputs.package_manager }}/deps/${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/bun.lockb') }}
          restore-keys: |
            r1/${{ runner.os }}/${{ inputs.package_manager }}/deps/

      - name: Install dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ~/.npmrc
        run: |
          case "${{ inputs.package_manager }}" in
            npm)
              npm ci
              ;;
            yarn)
              corepack enable
              yarn install --frozen-lockfile
              ;;
            bun)
              bun install --no-save
              ;;
            *)
              echo "Unknown package manager: ${{ inputs.package_manager }}"
              exit 1
              ;;
          esac

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Building for branch: $BRANCH_NAME"

          case "${{ inputs.package_manager }}" in
            npm)
              npm run build:$BRANCH_NAME
              ;;
            yarn)
              yarn build:$BRANCH_NAME
              ;;
            bun)
              bun run build:$BRANCH_NAME
              ;;
          esac

  publish:
    needs: [build, version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push version and tag
        run: |
          git add -u
          if ! git diff --cached --quiet; then
            git commit -m "version: ${{ needs.version.outputs.full_version }}"
          fi
          git tag -a "v${{ needs.version.outputs.full_version }}" -m "version: ${{ needs.version.outputs.full_version }}"
          git push origin HEAD:${{ github.ref_name }}
          git push origin "v${{ needs.version.outputs.full_version }}"

  deploy:
    needs: [build, publish, version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write build info
        run: |
          COMMIT="$(git rev-parse --short HEAD)"
          DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "version: ${{ needs.version.outputs.full_version }}" > build/build-info.txt
          echo "commit: $COMMIT" >> build/build-info.txt
          echo "date: $DATE" >> build/build-info.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          publish_branch: "build_${{ github.ref_name }}"
          publish_dir: build
          force_orphan: true
