name: Setup Package Name

on:
  workflow_call:
    secrets:
      ACCESS_GITHUB_TOKEN:
        required: true
    outputs:
      package_name:
        description: "Package name used in the workflow"
        value: ${{ jobs.setup-package-name.outputs.package_name }}

jobs:
  setup-package-name:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.define.outputs.package_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package name
        id: define
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
