name: Setup Branch

on:
  workflow_call:
    secrets:
      ACCESS_GITHUB_TOKEN:
        required: true
    outputs:  
      branch_name:
        description: "Branch name used in the workflow"
        value: ${{ jobs.setup-branch.outputs.branch_name }}

jobs:
  setup-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.define.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: define
        run: echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
